name: Build and Publish Release

on:
  workflow_run:
    workflows: ["CI / Build & Release"]
    types:
      - completed

jobs:
  build-and-publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTOR: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: write

    steps:
      # -----------------------------
      # 1️⃣ Checkout
      # -----------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -----------------------------
      # 2️⃣ Setup JDK
      # -----------------------------
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # -----------------------------
      # 3️⃣ Make Gradle wrapper executable
      # -----------------------------
      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      # -----------------------------
      # 4️⃣ Build ShadowJar
      # -----------------------------
      - name: Build ShadowJar
        run: ./gradlew shadowJar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # -----------------------------
      # 5️⃣ Create Release (если ещё нет)
      # -----------------------------
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v0.4.0
          release_name: v0.4.0
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      # -----------------------------
      # 6️⃣ Upload ShadowJar to Release
      # -----------------------------
      - name: Upload ShadowJar to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/libs/todo-app-0.4.0.jar
          asset_name: todo-app-0.4.0.jar
          asset_content_type: application/java-archive

      # -----------------------------
      # 7️⃣ Publish to GitHub Packages (Maven)
      # -----------------------------
      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
